name: cv-journey
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.4
  - torchvision=0.19
  - torchaudio=2.4
  - pytorch-cuda=12.4
  - jupyter
  - matplotlib
  - tqdm
  - pandas
  - numpy
  - scikit-image
  - pillow
  - pip
  - pip:
    - wandb
    - opencv-python
    - torchinfo          # modern replacement for torchsummary
    - pyyaml
    - pytorch-fid        # FID evaluation